{{- if eq .Values.ui.mode "standalone" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "soteria.fullname" . }}-console-reader
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
    app.kubernetes.io/component: console-standalone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "soteria.fullname" . }}-console-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "soteria.fullname" . }}-standalone
    namespace: {{ .Release.Namespace }}
{{- end }}
