{{- if eq .Values.ui.mode "standalone" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soteria.fullname" . }}-standalone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
    app.kubernetes.io/component: console-standalone
{{- end }}
