{{- if eq .Values.ui.mode "console-plugin" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-console-plugin-serving-cert" (include "soteria.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
    app.kubernetes.io/component: console-plugin
spec:
  secretName: {{ printf "%s-console-plugin-serving-cert" (include "soteria.fullname" .) | trunc 63 | trimSuffix "-" }}
  duration: 8760h
  renewBefore: 720h
  usages:
    - server auth
  issuerRef:
    name: {{ .Values.tls.issuerRef.name }}
    kind: {{ .Values.tls.issuerRef.kind }}
  dnsNames:
    - {{ printf "%s-console-plugin.%s.svc" (include "soteria.fullname" .) .Release.Namespace }}
    - {{ printf "%s-console-plugin.%s.svc.cluster.local" (include "soteria.fullname" .) .Release.Namespace }}
{{- end }}
