{{- if eq .Values.ui.mode "console-plugin" }}
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: soteria-console-plugin
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
    app.kubernetes.io/component: console-plugin
spec:
  displayName: "Soteria DR Management"
  backend:
    type: Service
    service:
      name: {{ printf "%s-console-plugin" (include "soteria.fullname" .) | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      port: 9443
{{- end }}
