{{- if eq .Values.ui.mode "console-plugin" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-console-plugin" (include "soteria.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
    app.kubernetes.io/component: console-plugin
spec:
  selector:
    {{- include "soteria.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: console-plugin
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      name: https
{{- end }}
