{{- /* ServiceAccount for the webhook server */ -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soteria-ip-rewrite.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soteria-ip-rewrite.labels" . | nindent 4 }}
