{{- if eq .Values.scylladb.mode "managed" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scylladb-serving
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
spec:
  secretName: scylladb-serving-tls
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
  issuerRef:
    name: {{ .Values.tls.issuerRef.name }}
    kind: {{ .Values.tls.issuerRef.kind }}
  commonName: {{ printf "%s-scylladb" (include "soteria.fullname" .) }}
  dnsNames:
    - "{{ printf "%s-scylladb-client.%s.svc" (include "soteria.fullname" .) .Release.Namespace }}"
    - "*.{{ printf "%s-scylladb.%s.svc.cluster.local" (include "soteria.fullname" .) .Release.Namespace }}"
    - "*.{{ printf "%s-scylladb-client.%s.svc" (include "soteria.fullname" .) .Release.Namespace }}"
    {{- if eq .Values.networking.mode "submariner" }}
    - "{{ printf "%s-scylladb-client.%s.svc.clusterset.local" (include "soteria.fullname" .) .Release.Namespace }}"
    - "*.{{ printf "%s-scylladb.%s.svc.clusterset.local" (include "soteria.fullname" .) .Release.Namespace }}"
    - "*.{{ printf "%s-scylladb-client.%s.svc.clusterset.local" (include "soteria.fullname" .) .Release.Namespace }}"
    {{- end }}
  usages:
    - server auth
    - client auth
{{- end }}
