{{- if and (eq .Values.scylladb.mode "managed") (eq .Values.networking.mode "submariner") }}
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: {{ printf "%s-scylladb-client" (include "soteria.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
{{- end }}
